//go:build windows

// Code generated by MockGen. DO NOT EDIT.
// Source: ports_windows.go
//
// Generated by this command:
//
//	mockgen -source=ports_windows.go -destination=ports_windows_mock_test.go -package=controlpipe -build_constraint=windows
//

// Package controlpipe is a generated GoMock package.
package controlpipe

import (
	context "context"
	net "net"
	reflect "reflect"

	hub "github.com/nokamoto/agent-pulse-hub/internal/application/hub"
	domain "github.com/nokamoto/agent-pulse-hub/internal/domain"
	jsonvalue "github.com/nokamoto/agent-pulse-hub/internal/domain/jsonvalue"
	gomock "go.uber.org/mock/gomock"
)

// Mockregistrar is a mock of registrar interface.
type Mockregistrar struct {
	ctrl     *gomock.Controller
	recorder *MockregistrarMockRecorder
	isgomock struct{}
}

// MockregistrarMockRecorder is the mock recorder for Mockregistrar.
type MockregistrarMockRecorder struct {
	mock *Mockregistrar
}

// NewMockregistrar creates a new mock instance.
func NewMockregistrar(ctrl *gomock.Controller) *Mockregistrar {
	mock := &Mockregistrar{ctrl: ctrl}
	mock.recorder = &MockregistrarMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockregistrar) EXPECT() *MockregistrarMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *Mockregistrar) Register(arg0, arg1 string, arg2 *jsonvalue.Value) (domain.SubscriptionID, *hub.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.SubscriptionID)
	ret1, _ := ret[1].(*hub.Error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockregistrarMockRecorder) Register(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*Mockregistrar)(nil).Register), arg0, arg1, arg2)
}

// MockpipeSystem is a mock of pipeSystem interface.
type MockpipeSystem struct {
	ctrl     *gomock.Controller
	recorder *MockpipeSystemMockRecorder
	isgomock struct{}
}

// MockpipeSystemMockRecorder is the mock recorder for MockpipeSystem.
type MockpipeSystemMockRecorder struct {
	mock *MockpipeSystem
}

// NewMockpipeSystem creates a new mock instance.
func NewMockpipeSystem(ctrl *gomock.Controller) *MockpipeSystem {
	mock := &MockpipeSystem{ctrl: ctrl}
	mock.recorder = &MockpipeSystemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpipeSystem) EXPECT() *MockpipeSystemMockRecorder {
	return m.recorder
}

// CurrentUserSID mocks base method.
func (m *MockpipeSystem) CurrentUserSID() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentUserSID")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentUserSID indicates an expected call of CurrentUserSID.
func (mr *MockpipeSystemMockRecorder) CurrentUserSID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentUserSID", reflect.TypeOf((*MockpipeSystem)(nil).CurrentUserSID))
}

// Dial mocks base method.
func (m *MockpipeSystem) Dial(arg0 context.Context, arg1 string) (net.Conn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dial", arg0, arg1)
	ret0, _ := ret[0].(net.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dial indicates an expected call of Dial.
func (mr *MockpipeSystemMockRecorder) Dial(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dial", reflect.TypeOf((*MockpipeSystem)(nil).Dial), arg0, arg1)
}

// Listen mocks base method.
func (m *MockpipeSystem) Listen(arg0, arg1 string) (net.Listener, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Listen", arg0, arg1)
	ret0, _ := ret[0].(net.Listener)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Listen indicates an expected call of Listen.
func (mr *MockpipeSystemMockRecorder) Listen(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Listen", reflect.TypeOf((*MockpipeSystem)(nil).Listen), arg0, arg1)
}

// ServerUserSID mocks base method.
func (m *MockpipeSystem) ServerUserSID(arg0 net.Conn) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServerUserSID", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServerUserSID indicates an expected call of ServerUserSID.
func (mr *MockpipeSystemMockRecorder) ServerUserSID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServerUserSID", reflect.TypeOf((*MockpipeSystem)(nil).ServerUserSID), arg0)
}
