// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=service_mock_test.go -package=hub
//

// Package hub is a generated GoMock package.
package hub

import (
	context "context"
	reflect "reflect"

	domain "github.com/nokamoto/agent-pulse-hub/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPluginPort is a mock of PluginPort interface.
type MockPluginPort struct {
	ctrl     *gomock.Controller
	recorder *MockPluginPortMockRecorder
	isgomock struct{}
}

// MockPluginPortMockRecorder is the mock recorder for MockPluginPort.
type MockPluginPortMockRecorder struct {
	mock *MockPluginPort
}

// NewMockPluginPort creates a new mock instance.
func NewMockPluginPort(ctrl *gomock.Controller) *MockPluginPort {
	mock := &MockPluginPort{ctrl: ctrl}
	mock.recorder = &MockPluginPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPluginPort) EXPECT() *MockPluginPortMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockPluginPort) Start(arg0 context.Context, arg1 PluginHandlers) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockPluginPortMockRecorder) Start(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockPluginPort)(nil).Start), arg0, arg1)
}

// Stop mocks base method.
func (m *MockPluginPort) Stop(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockPluginPortMockRecorder) Stop(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockPluginPort)(nil).Stop), arg0)
}

// Watch mocks base method.
func (m *MockPluginPort) Watch(arg0 context.Context, arg1 WatchRequest, arg2 func() error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Watch indicates an expected call of Watch.
func (mr *MockPluginPortMockRecorder) Watch(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockPluginPort)(nil).Watch), arg0, arg1, arg2)
}

// MockDeliveryPort is a mock of DeliveryPort interface.
type MockDeliveryPort struct {
	ctrl     *gomock.Controller
	recorder *MockDeliveryPortMockRecorder
	isgomock struct{}
}

// MockDeliveryPortMockRecorder is the mock recorder for MockDeliveryPort.
type MockDeliveryPortMockRecorder struct {
	mock *MockDeliveryPort
}

// NewMockDeliveryPort creates a new mock instance.
func NewMockDeliveryPort(ctrl *gomock.Controller) *MockDeliveryPort {
	mock := &MockDeliveryPort{ctrl: ctrl}
	mock.recorder = &MockDeliveryPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeliveryPort) EXPECT() *MockDeliveryPortMockRecorder {
	return m.recorder
}

// Deliver mocks base method.
func (m *MockDeliveryPort) Deliver(arg0 context.Context, arg1 domain.Event) DeliveryResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deliver", arg0, arg1)
	ret0, _ := ret[0].(DeliveryResult)
	return ret0
}

// Deliver indicates an expected call of Deliver.
func (mr *MockDeliveryPortMockRecorder) Deliver(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deliver", reflect.TypeOf((*MockDeliveryPort)(nil).Deliver), arg0, arg1)
}
