//go:build windows

// Code generated by MockGen. DO NOT EDIT.
// Source: filesystem_windows.go
//
// Generated by this command:
//
//	mockgen -source=filesystem_windows.go -destination=filesystem_windows_mock_test.go -package=manualplugin -build_constraint=windows
//

// Package manualplugin is a generated GoMock package.
package manualplugin

import (
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MocktriggerFiles is a mock of triggerFiles interface.
type MocktriggerFiles struct {
	ctrl     *gomock.Controller
	recorder *MocktriggerFilesMockRecorder
	isgomock struct{}
}

// MocktriggerFilesMockRecorder is the mock recorder for MocktriggerFiles.
type MocktriggerFilesMockRecorder struct {
	mock *MocktriggerFiles
}

// NewMocktriggerFiles creates a new mock instance.
func NewMocktriggerFiles(ctrl *gomock.Controller) *MocktriggerFiles {
	mock := &MocktriggerFiles{ctrl: ctrl}
	mock.recorder = &MocktriggerFilesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktriggerFiles) EXPECT() *MocktriggerFilesMockRecorder {
	return m.recorder
}

// Claim mocks base method.
func (m *MocktriggerFiles) Claim(target watchTarget) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Claim", target)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Claim indicates an expected call of Claim.
func (mr *MocktriggerFilesMockRecorder) Claim(target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Claim", reflect.TypeOf((*MocktriggerFiles)(nil).Claim), target)
}

// DirectoryKey mocks base method.
func (m *MocktriggerFiles) DirectoryKey(parent, name string) (targetKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DirectoryKey", parent, name)
	ret0, _ := ret[0].(targetKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DirectoryKey indicates an expected call of DirectoryKey.
func (mr *MocktriggerFilesMockRecorder) DirectoryKey(parent, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DirectoryKey", reflect.TypeOf((*MocktriggerFiles)(nil).DirectoryKey), parent, name)
}

// Exists mocks base method.
func (m *MocktriggerFiles) Exists(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Exists indicates an expected call of Exists.
func (mr *MocktriggerFilesMockRecorder) Exists(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MocktriggerFiles)(nil).Exists), path)
}

// LocalDrive mocks base method.
func (m *MocktriggerFiles) LocalDrive(root string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LocalDrive", root)
	ret0, _ := ret[0].(bool)
	return ret0
}

// LocalDrive indicates an expected call of LocalDrive.
func (mr *MocktriggerFilesMockRecorder) LocalDrive(root any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LocalDrive", reflect.TypeOf((*MocktriggerFiles)(nil).LocalDrive), root)
}

// Open mocks base method.
func (m *MocktriggerFiles) Open(path string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", path)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MocktriggerFilesMockRecorder) Open(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MocktriggerFiles)(nil).Open), path)
}

// Remove mocks base method.
func (m *MocktriggerFiles) Remove(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MocktriggerFilesMockRecorder) Remove(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MocktriggerFiles)(nil).Remove), path)
}
