//go:build windows

// Code generated by MockGen. DO NOT EDIT.
// Source: ports_windows.go
//
// Generated by this command:
//
//	mockgen -source=ports_windows.go -destination=ports_windows_mock_test.go -package=pluginprocess -build_constraint=windows
//

// Package pluginprocess is a generated GoMock package.
package pluginprocess

import (
	io "io"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockchildProcess is a mock of childProcess interface.
type MockchildProcess struct {
	ctrl     *gomock.Controller
	recorder *MockchildProcessMockRecorder
	isgomock struct{}
}

// MockchildProcessMockRecorder is the mock recorder for MockchildProcess.
type MockchildProcessMockRecorder struct {
	mock *MockchildProcess
}

// NewMockchildProcess creates a new mock instance.
func NewMockchildProcess(ctrl *gomock.Controller) *MockchildProcess {
	mock := &MockchildProcess{ctrl: ctrl}
	mock.recorder = &MockchildProcessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockchildProcess) EXPECT() *MockchildProcessMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockchildProcess) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockchildProcessMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockchildProcess)(nil).Close))
}

// Stderr mocks base method.
func (m *MockchildProcess) Stderr() io.ReadCloser {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stderr")
	ret0, _ := ret[0].(io.ReadCloser)
	return ret0
}

// Stderr indicates an expected call of Stderr.
func (mr *MockchildProcessMockRecorder) Stderr() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stderr", reflect.TypeOf((*MockchildProcess)(nil).Stderr))
}

// Stdin mocks base method.
func (m *MockchildProcess) Stdin() io.WriteCloser {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stdin")
	ret0, _ := ret[0].(io.WriteCloser)
	return ret0
}

// Stdin indicates an expected call of Stdin.
func (mr *MockchildProcessMockRecorder) Stdin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stdin", reflect.TypeOf((*MockchildProcess)(nil).Stdin))
}

// Stdout mocks base method.
func (m *MockchildProcess) Stdout() io.ReadCloser {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stdout")
	ret0, _ := ret[0].(io.ReadCloser)
	return ret0
}

// Stdout indicates an expected call of Stdout.
func (mr *MockchildProcessMockRecorder) Stdout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stdout", reflect.TypeOf((*MockchildProcess)(nil).Stdout))
}

// Terminate mocks base method.
func (m *MockchildProcess) Terminate() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Terminate")
}

// Terminate indicates an expected call of Terminate.
func (mr *MockchildProcessMockRecorder) Terminate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Terminate", reflect.TypeOf((*MockchildProcess)(nil).Terminate))
}

// Wait mocks base method.
func (m *MockchildProcess) Wait() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait")
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockchildProcessMockRecorder) Wait() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockchildProcess)(nil).Wait))
}

// MockprocessLauncher is a mock of processLauncher interface.
type MockprocessLauncher struct {
	ctrl     *gomock.Controller
	recorder *MockprocessLauncherMockRecorder
	isgomock struct{}
}

// MockprocessLauncherMockRecorder is the mock recorder for MockprocessLauncher.
type MockprocessLauncherMockRecorder struct {
	mock *MockprocessLauncher
}

// NewMockprocessLauncher creates a new mock instance.
func NewMockprocessLauncher(ctrl *gomock.Controller) *MockprocessLauncher {
	mock := &MockprocessLauncher{ctrl: ctrl}
	mock.recorder = &MockprocessLauncherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprocessLauncher) EXPECT() *MockprocessLauncherMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockprocessLauncher) Start(arg0 Config) (childProcess, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(childProcess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockprocessLauncherMockRecorder) Start(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockprocessLauncher)(nil).Start), arg0)
}

// Mocktimer is a mock of timer interface.
type Mocktimer struct {
	ctrl     *gomock.Controller
	recorder *MocktimerMockRecorder
	isgomock struct{}
}

// MocktimerMockRecorder is the mock recorder for Mocktimer.
type MocktimerMockRecorder struct {
	mock *Mocktimer
}

// NewMocktimer creates a new mock instance.
func NewMocktimer(ctrl *gomock.Controller) *Mocktimer {
	mock := &Mocktimer{ctrl: ctrl}
	mock.recorder = &MocktimerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocktimer) EXPECT() *MocktimerMockRecorder {
	return m.recorder
}

// C mocks base method.
func (m *Mocktimer) C() <-chan time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "C")
	ret0, _ := ret[0].(<-chan time.Time)
	return ret0
}

// C indicates an expected call of C.
func (mr *MocktimerMockRecorder) C() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "C", reflect.TypeOf((*Mocktimer)(nil).C))
}

// Stop mocks base method.
func (m *Mocktimer) Stop() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MocktimerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*Mocktimer)(nil).Stop))
}

// Mockclock is a mock of clock interface.
type Mockclock struct {
	ctrl     *gomock.Controller
	recorder *MockclockMockRecorder
	isgomock struct{}
}

// MockclockMockRecorder is the mock recorder for Mockclock.
type MockclockMockRecorder struct {
	mock *Mockclock
}

// NewMockclock creates a new mock instance.
func NewMockclock(ctrl *gomock.Controller) *Mockclock {
	mock := &Mockclock{ctrl: ctrl}
	mock.recorder = &MockclockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockclock) EXPECT() *MockclockMockRecorder {
	return m.recorder
}

// NewTimer mocks base method.
func (m *Mockclock) NewTimer(arg0 time.Duration) timer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewTimer", arg0)
	ret0, _ := ret[0].(timer)
	return ret0
}

// NewTimer indicates an expected call of NewTimer.
func (mr *MockclockMockRecorder) NewTimer(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTimer", reflect.TypeOf((*Mockclock)(nil).NewTimer), arg0)
}

// Now mocks base method.
func (m *Mockclock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockclockMockRecorder) Now() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*Mockclock)(nil).Now))
}
