//go:build windows

// Code generated by MockGen. DO NOT EDIT.
// Source: ports_windows.go
//
// Generated by this command:
//
//	mockgen -source=ports_windows.go -destination=ports_windows_mock_test.go -package=windowsprocess -build_constraint=windows
//

// Package windowsprocess is a generated GoMock package.
package windowsprocess

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	windows "golang.org/x/sys/windows"
)

// MocknativeProcess is a mock of nativeProcess interface.
type MocknativeProcess struct {
	ctrl     *gomock.Controller
	recorder *MocknativeProcessMockRecorder
	isgomock struct{}
}

// MocknativeProcessMockRecorder is the mock recorder for MocknativeProcess.
type MocknativeProcessMockRecorder struct {
	mock *MocknativeProcess
}

// NewMocknativeProcess creates a new mock instance.
func NewMocknativeProcess(ctrl *gomock.Controller) *MocknativeProcess {
	mock := &MocknativeProcess{ctrl: ctrl}
	mock.recorder = &MocknativeProcessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknativeProcess) EXPECT() *MocknativeProcessMockRecorder {
	return m.recorder
}

// Kill mocks base method.
func (m *MocknativeProcess) Kill() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Kill")
	ret0, _ := ret[0].(error)
	return ret0
}

// Kill indicates an expected call of Kill.
func (mr *MocknativeProcessMockRecorder) Kill() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Kill", reflect.TypeOf((*MocknativeProcess)(nil).Kill))
}

// PID mocks base method.
func (m *MocknativeProcess) PID() uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PID")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// PID indicates an expected call of PID.
func (mr *MocknativeProcessMockRecorder) PID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PID", reflect.TypeOf((*MocknativeProcess)(nil).PID))
}

// SetCancel mocks base method.
func (m *MocknativeProcess) SetCancel(arg0 func() error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCancel", arg0)
}

// SetCancel indicates an expected call of SetCancel.
func (mr *MocknativeProcessMockRecorder) SetCancel(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCancel", reflect.TypeOf((*MocknativeProcess)(nil).SetCancel), arg0)
}

// Start mocks base method.
func (m *MocknativeProcess) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MocknativeProcessMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MocknativeProcess)(nil).Start))
}

// Wait mocks base method.
func (m *MocknativeProcess) Wait() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait")
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MocknativeProcessMockRecorder) Wait() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MocknativeProcess)(nil).Wait))
}

// MocknativeSystem is a mock of nativeSystem interface.
type MocknativeSystem struct {
	ctrl     *gomock.Controller
	recorder *MocknativeSystemMockRecorder
	isgomock struct{}
}

// MocknativeSystemMockRecorder is the mock recorder for MocknativeSystem.
type MocknativeSystemMockRecorder struct {
	mock *MocknativeSystem
}

// NewMocknativeSystem creates a new mock instance.
func NewMocknativeSystem(ctrl *gomock.Controller) *MocknativeSystem {
	mock := &MocknativeSystem{ctrl: ctrl}
	mock.recorder = &MocknativeSystemMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknativeSystem) EXPECT() *MocknativeSystemMockRecorder {
	return m.recorder
}

// Assign mocks base method.
func (m *MocknativeSystem) Assign(arg0 windows.Handle, arg1 uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assign", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Assign indicates an expected call of Assign.
func (mr *MocknativeSystemMockRecorder) Assign(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assign", reflect.TypeOf((*MocknativeSystem)(nil).Assign), arg0, arg1)
}

// CloseJob mocks base method.
func (m *MocknativeSystem) CloseJob(arg0 windows.Handle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseJob", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseJob indicates an expected call of CloseJob.
func (mr *MocknativeSystemMockRecorder) CloseJob(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseJob", reflect.TypeOf((*MocknativeSystem)(nil).CloseJob), arg0)
}

// CreateJob mocks base method.
func (m *MocknativeSystem) CreateJob() (windows.Handle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJob")
	ret0, _ := ret[0].(windows.Handle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJob indicates an expected call of CreateJob.
func (mr *MocknativeSystemMockRecorder) CreateJob() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJob", reflect.TypeOf((*MocknativeSystem)(nil).CreateJob))
}

// NewCommand mocks base method.
func (m *MocknativeSystem) NewCommand(arg0 context.Context, arg1 string, arg2 []string, arg3 io.Reader, arg4, arg5 io.Writer) nativeProcess {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewCommand", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(nativeProcess)
	return ret0
}

// NewCommand indicates an expected call of NewCommand.
func (mr *MocknativeSystemMockRecorder) NewCommand(arg0, arg1, arg2, arg3, arg4, arg5 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCommand", reflect.TypeOf((*MocknativeSystem)(nil).NewCommand), arg0, arg1, arg2, arg3, arg4, arg5)
}

// Resume mocks base method.
func (m *MocknativeSystem) Resume(arg0 uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resume", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resume indicates an expected call of Resume.
func (mr *MocknativeSystemMockRecorder) Resume(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resume", reflect.TypeOf((*MocknativeSystem)(nil).Resume), arg0)
}

// TerminateJob mocks base method.
func (m *MocknativeSystem) TerminateJob(arg0 windows.Handle) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TerminateJob", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// TerminateJob indicates an expected call of TerminateJob.
func (mr *MocknativeSystemMockRecorder) TerminateJob(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TerminateJob", reflect.TypeOf((*MocknativeSystem)(nil).TerminateJob), arg0)
}
