// Code generated by MockGen. DO NOT EDIT.
// Source: main_windows.go
//
// Generated by this command:
//
//	mockgen -source=main_windows.go -destination=command_mock_windows_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	io "io"
	os "os"
	reflect "reflect"

	controlpipe "github.com/nokamoto/agent-pulse-hub/internal/adapters/controlpipe"
	jsonvalue "github.com/nokamoto/agent-pulse-hub/internal/domain/jsonvalue"
	gomock "go.uber.org/mock/gomock"
)

// MockcommandOperations is a mock of commandOperations interface.
type MockcommandOperations struct {
	ctrl     *gomock.Controller
	recorder *MockcommandOperationsMockRecorder
	isgomock struct{}
}

// MockcommandOperationsMockRecorder is the mock recorder for MockcommandOperations.
type MockcommandOperationsMockRecorder struct {
	mock *MockcommandOperations
}

// NewMockcommandOperations creates a new mock instance.
func NewMockcommandOperations(ctrl *gomock.Controller) *MockcommandOperations {
	mock := &MockcommandOperations{ctrl: ctrl}
	mock.recorder = &MockcommandOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcommandOperations) EXPECT() *MockcommandOperationsMockRecorder {
	return m.recorder
}

// Daemon mocks base method.
func (m *MockcommandOperations) Daemon(arg0 string, arg1 io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Daemon", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Daemon indicates an expected call of Daemon.
func (mr *MockcommandOperationsMockRecorder) Daemon(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Daemon", reflect.TypeOf((*MockcommandOperations)(nil).Daemon), arg0, arg1)
}

// LookupEnv mocks base method.
func (m *MockcommandOperations) LookupEnv(arg0 string) (string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupEnv", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// LookupEnv indicates an expected call of LookupEnv.
func (mr *MockcommandOperationsMockRecorder) LookupEnv(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupEnv", reflect.TypeOf((*MockcommandOperations)(nil).LookupEnv), arg0)
}

// Register mocks base method.
func (m *MockcommandOperations) Register(arg0 context.Context, arg1, arg2 string, arg3 *jsonvalue.Value) (controlpipe.RegistrationResponse, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(controlpipe.RegistrationResponse)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Register indicates an expected call of Register.
func (mr *MockcommandOperationsMockRecorder) Register(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockcommandOperations)(nil).Register), arg0, arg1, arg2, arg3)
}

// WatchArguments mocks base method.
func (m *MockcommandOperations) WatchArguments(arg0 string) (*jsonvalue.Value, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchArguments", arg0)
	ret0, _ := ret[0].(*jsonvalue.Value)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchArguments indicates an expected call of WatchArguments.
func (mr *MockcommandOperationsMockRecorder) WatchArguments(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchArguments", reflect.TypeOf((*MockcommandOperations)(nil).WatchArguments), arg0)
}

// MockwatchFiles is a mock of watchFiles interface.
type MockwatchFiles struct {
	ctrl     *gomock.Controller
	recorder *MockwatchFilesMockRecorder
	isgomock struct{}
}

// MockwatchFilesMockRecorder is the mock recorder for MockwatchFiles.
type MockwatchFilesMockRecorder struct {
	mock *MockwatchFiles
}

// NewMockwatchFiles creates a new mock instance.
func NewMockwatchFiles(ctrl *gomock.Controller) *MockwatchFiles {
	mock := &MockwatchFiles{ctrl: ctrl}
	mock.recorder = &MockwatchFilesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockwatchFiles) EXPECT() *MockwatchFilesMockRecorder {
	return m.recorder
}

// Open mocks base method.
func (m *MockwatchFiles) Open(arg0 string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", arg0)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockwatchFilesMockRecorder) Open(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockwatchFiles)(nil).Open), arg0)
}

// Stat mocks base method.
func (m *MockwatchFiles) Stat(arg0 string) (os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", arg0)
	ret0, _ := ret[0].(os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockwatchFilesMockRecorder) Stat(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockwatchFiles)(nil).Stat), arg0)
}
