//go:build windows

// Code generated by MockGen. DO NOT EDIT.
// Source: ports_windows.go
//
// Generated by this command:
//
//	mockgen -source=ports_windows.go -destination=ports_windows_mock_test.go -package=codex -build_constraint=windows
//

// Package codex is a generated GoMock package.
package codex

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockcommandProcess is a mock of commandProcess interface.
type MockcommandProcess struct {
	ctrl     *gomock.Controller
	recorder *MockcommandProcessMockRecorder
	isgomock struct{}
}

// MockcommandProcessMockRecorder is the mock recorder for MockcommandProcess.
type MockcommandProcessMockRecorder struct {
	mock *MockcommandProcess
}

// NewMockcommandProcess creates a new mock instance.
func NewMockcommandProcess(ctrl *gomock.Controller) *MockcommandProcess {
	mock := &MockcommandProcess{ctrl: ctrl}
	mock.recorder = &MockcommandProcessMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcommandProcess) EXPECT() *MockcommandProcessMockRecorder {
	return m.recorder
}

// Wait mocks base method.
func (m *MockcommandProcess) Wait() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait")
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockcommandProcessMockRecorder) Wait() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*MockcommandProcess)(nil).Wait))
}

// MockcommandLauncher is a mock of commandLauncher interface.
type MockcommandLauncher struct {
	ctrl     *gomock.Controller
	recorder *MockcommandLauncherMockRecorder
	isgomock struct{}
}

// MockcommandLauncherMockRecorder is the mock recorder for MockcommandLauncher.
type MockcommandLauncherMockRecorder struct {
	mock *MockcommandLauncher
}

// NewMockcommandLauncher creates a new mock instance.
func NewMockcommandLauncher(ctrl *gomock.Controller) *MockcommandLauncher {
	mock := &MockcommandLauncher{ctrl: ctrl}
	mock.recorder = &MockcommandLauncherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcommandLauncher) EXPECT() *MockcommandLauncherMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockcommandLauncher) Start(arg0 context.Context, arg1 string, arg2 []string, arg3, arg4 io.Writer) (commandProcess, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(commandProcess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockcommandLauncherMockRecorder) Start(arg0, arg1, arg2, arg3, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockcommandLauncher)(nil).Start), arg0, arg1, arg2, arg3, arg4)
}

// MocktimeoutSource is a mock of timeoutSource interface.
type MocktimeoutSource struct {
	ctrl     *gomock.Controller
	recorder *MocktimeoutSourceMockRecorder
	isgomock struct{}
}

// MocktimeoutSourceMockRecorder is the mock recorder for MocktimeoutSource.
type MocktimeoutSourceMockRecorder struct {
	mock *MocktimeoutSource
}

// NewMocktimeoutSource creates a new mock instance.
func NewMocktimeoutSource(ctrl *gomock.Controller) *MocktimeoutSource {
	mock := &MocktimeoutSource{ctrl: ctrl}
	mock.recorder = &MocktimeoutSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktimeoutSource) EXPECT() *MocktimeoutSourceMockRecorder {
	return m.recorder
}

// WithTimeout mocks base method.
func (m *MocktimeoutSource) WithTimeout(arg0 context.Context, arg1 time.Duration) (context.Context, context.CancelFunc) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTimeout", arg0, arg1)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(context.CancelFunc)
	return ret0, ret1
}

// WithTimeout indicates an expected call of WithTimeout.
func (mr *MocktimeoutSourceMockRecorder) WithTimeout(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTimeout", reflect.TypeOf((*MocktimeoutSource)(nil).WithTimeout), arg0, arg1)
}
