name: Guardrails

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  guardrails:
    name: Run Guardrails
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.21'

      - name: Download Go dependencies
        run: go mod download

      - name: Run guardrails
        run: go run build/mage.go -d build -w . guardrails
